-- Generated by Gemini.

-- Custom ENUM types
CREATE TYPE "iot_field_type" AS ENUM (
    'BOOLEAN',
    'NUMBER',
    'STRING'
);

CREATE TYPE "iot_source_type" AS ENUM (
    'HTTP',
    'MAS-MONITOR',
    'MQTT'
);

CREATE TYPE "iot_unit" AS ENUM (
    'AMOUNT',
    'AMPERE',
    'BOOLEAN',
    'CUBIC_METER',
    'DEGREES_CELCIUS',
    'METER_PER_SECOND',
    'PERCENT',
    'STRING',
    'VOLT',
    'WATT',
    'WATT_HOUR'
);

-- Table Definitions
CREATE TABLE "site" (
    "id" SERIAL PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "description" TEXT NOT NULL,
    "location" JSONB NOT NULL,
    "public" BOOLEAN NOT NULL,
    "initial_view" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "iot_flow" (
    "id" SERIAL PRIMARY KEY,
    "site_id" INTEGER NOT NULL REFERENCES "site"("id"),
    "name" TEXT NOT NULL UNIQUE,
    "nodes" JSONB NOT NULL,
    "edges" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "iot_deployment" (
    "id" SERIAL PRIMARY KEY,
    "flow_id" INTEGER NOT NULL UNIQUE REFERENCES "iot_flow"("id"),
    "deployed_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "nodes" JSONB NOT NULL,
    "edges" JSONB NOT NULL
);

CREATE TABLE "flow_error" (
    "id" SERIAL PRIMARY KEY,
    "flow_id" INTEGER NOT NULL REFERENCES "iot_flow"("id") ON DELETE CASCADE,
    "node_id" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "timestamp" TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE "iot_flow_debug_message" (
    "id" SERIAL PRIMARY KEY,
    "flow_id" INTEGER NOT NULL REFERENCES "iot_flow"("id") ON DELETE CASCADE,
    "debug_node_id" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "debug_messages" (
    "id" SERIAL PRIMARY KEY,
    "flow_id" INTEGER NOT NULL,
    "debug_node_id" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE "iot_source" (
    "id" SERIAL PRIMARY KEY,
    "site_id" INTEGER NOT NULL REFERENCES "site"("id"),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" iot_source_type NOT NULL,
    "config" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "sensor" (
    "id" SERIAL PRIMARY KEY,
    "flow_id" INTEGER REFERENCES "iot_flow"("id") ON DELETE SET NULL,
    "identifier" TEXT NOT NULL,
    "measuring" TEXT NOT NULL,
    "unit" iot_unit NOT NULL,
    "value_type" iot_field_type NOT NULL
);

-- Note: 'sensors' table appears to be a duplicate or older version of 'sensor'. Including it as defined.
CREATE TABLE "sensors" (
    "id" SERIAL PRIMARY KEY,
    "flow_id" INTEGER,
    "identifier" TEXT NOT NULL,
    "measuring" TEXT NOT NULL,
    "unit" iot_unit NOT NULL,
    "value_type" iot_field_type NOT NULL
);


CREATE TABLE "reading" (
    "id" SERIAL PRIMARY KEY,
    "sensor_id" INTEGER NOT NULL REFERENCES "sensor"("id") ON DELETE CASCADE,
    "timestamp" TIMESTAMPTZ NOT NULL,
    "raw_value" TEXT NOT NULL,
    "value" DOUBLE PRECISION
);

CREATE TABLE "sensor_metadata" (
    "id" SERIAL PRIMARY KEY,
    "sensor_id" INTEGER NOT NULL REFERENCES "sensor"("id") ON DELETE CASCADE,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL
);