//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "iot_flow_debug_message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub flow_id: i32,
    #[sea_orm(column_type = "Text")]
    pub debug_node_id: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::iot_flow::Entity",
        from = "Column::FlowId",
        to = "super::iot_flow::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IotFlow,
}

impl Related<super::iot_flow::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IotFlow.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
