//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "iot_deployment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub flow_id: i32,
    pub deployed_at: DateTime,
    #[sea_orm(column_type = "JsonBinary")]
    pub nodes: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub edges: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::iot_flow::Entity",
        from = "Column::FlowId",
        to = "super::iot_flow::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    IotFlow,
}

impl Related<super::iot_flow::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IotFlow.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}