//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reading")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sensor_id: i32,
    pub timestamp: chrono::DateTime<chrono::Utc>,
    #[sea_orm(column_type = "Text")]
    pub raw_value: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub value: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sensor::Entity",
        from = "Column::SensorId",
        to = "super::sensor::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Sensor,
}

impl Related<super::sensor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sensor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}