---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iot.visualiseinfo.com
  resources:
  - iotlistenerrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.visualiseinfo.com
  resources:
  - iotlistenerrequests/finalizers
  verbs:
  - update
- apiGroups:
  - iot.visualiseinfo.com
  resources:
  - iotlistenerrequests/status
  verbs:
  - get
  - patch
  - update
