apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      # Pod 级别的安全上下文
      securityContext:
        runAsNonRoot: true
        fsGroup: 65534
        # seccompProfile:
        #   type: RuntimeDefault
      
      # 定义 Pod 可以使用的卷 (Volumes)
      volumes:
      - name: config-volume
        configMap:
          name: listener-operator-config # 对应我们创建的 ConfigMap
      - name: secret-volume
        secret:
          secretName: listener-operator-secrets # 对应我们创建的 Secret
          
      # 容器列表
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        
        # 将上面定义的卷挂载到容器内部
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config # 挂载配置
        - name: secret-volume
          mountPath: /etc/secrets # 挂载密钥
          
        # 容器级别的安全上下文
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
            
        # 健康检查探针
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          
        # 资源请求和限制
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
            
      # Pod 使用的服务账户
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10