apiVersion: v1
kind: Service
metadata:
  name: kafka
  annotations:
    # This ensures the service gets a stable cluster IP
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP  # Use ClusterIP instead of default to be explicit